name: Test

permissions:
  contents: read

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
      with:
        node-version: '22'

    - name: Install dependencies
      run: yarn

    - name: Run Tests
      run: yarn run test